### ISSUE TITLE
App closes upon barcode scan

### ISSUE THREAD

**Issue by joakimmag** [Scandit/datacapture-xamarin-forms-samples#1]
Hi,

When I run BarcodeCaptureSimpleSample.iOS on iPhone - when I place a barcode inside the view, the app immediately exits.

It happens every time. When I debug from VS it does not break or show an error.

**Comment by ScanditSupport** [comment]
Hi @joakimmag,

My apologies, could you please confirm, would the crash happen for you if you remove the following lines?
https://github.com/Scandit/datacapture-xamarin-forms-samples/blob/master/forms/BarcodeCaptureSimpleSample/BarcodeCaptureSimpleSample/ViewModels/MainPageViewModel.cs#L135-L141

Seems that this crash is simply connected to the message presentation, could you please please get in contact with us directly via: [Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)?

**Comment by joakimmag** [comment]
Thank you for your response. The crash did not happen when I removed the lines. Further, the crash did not happen - and the popup message worked fine - when I added back the lines and set Linker Behavior to _Don't Link_ or _Link Framework SDKs Only_ in iOS Build Settings.

**Comment by ScanditSupport** [comment]
Hi @joakimmag,

Thank you for noting, we will modify the linker behavior of the samples in the future update.
